apiVersion: v1
items:
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    annotations:
      deployment.kubernetes.io/revision: "1"
    creationTimestamp: "2023-04-19T06:12:58Z"
    generation: 1
    labels:
      app: item-service
    name: item-service
    namespace: default
  spec:
    progressDeadlineSeconds: 600
    replicas: 1
    revisionHistoryLimit: 10
    selector:
      matchLabels:
        app: item-service
    strategy:
      rollingUpdate:
        maxSurge: 25%
        maxUnavailable: 25%
      type: RollingUpdate
    template:
      metadata:
        creationTimestamp: null
        labels:
          app: item-service
      spec:
        containers:
        - image: itsnesskhan/k8s-item-service:0.0.1-SNAPSHOT
          imagePullPolicy: IfNotPresent
          name: k8s-item-service
          env:
          - name: MYSQL_HOST
            value: mysql
          - name: MYSQL_PORT
            value: "3306"
          - name: MYSQL_USERNAME
            value: root
          - name: MYSQL_PASSWORD
            value: root  
          ports:
           - containerPort: 8081      
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
kind: List
metadata:
  resourceVersion: ""

---

apiVersion: v1
items:
- apiVersion: v1
  kind: Service
  metadata:
    creationTimestamp: "2023-04-19T06:13:07Z"
    labels:
      app: item-service
    name: item-service
    namespace: default
  spec:
    allocateLoadBalancerNodePorts: true
    clusterIP: 10.110.58.113
    clusterIPs:
    - 10.110.58.113
    externalTrafficPolicy: Cluster
    internalTrafficPolicy: Cluster
    ipFamilies:
    - IPv4
    ipFamilyPolicy: SingleStack
    ports:
    - nodePort: 32301
      port: 8081
      protocol: TCP
      targetPort: 8081
    selector:
      app: item-service
    sessionAffinity: None
    type: LoadBalancer
kind: List
metadata:
  resourceVersion: ""
  
  