apiVersion: v1
kind: List
metadata:
  resourceVersion: ""
items:
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: order-service
    namespace: default
    labels:
      app: order-service
    annotations:
      deployment.kubernetes.io/revision: "1"
    creationTimestamp: "2023-04-19T07:03:29Z"
    generation: 1
  spec:
    replicas: 1
    selector:
      matchLabels:
        app: order-service
    template:
      metadata:
        labels:
          app: order-service
      spec:
        containers:
        - name: k8s-order-service
          image: itsnesskhan/k8s-order-service:0.0.1-SNAPSHOT
          imagePullPolicy: IfNotPresent
          env:
          - name: MYSQL_HOST
            value: mysql
          - name: MYSQL_PORT
            value: "3306"
          - name: MYSQL_USERNAME
            value: root
          - name: MYSQL_PASSWORD
            value: root 
          - name: ITEM_SERVICE_URI
            value: http://item-service  
          ports:
          - containerPort: 8080         
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
        affinity: {}
        tolerations: []
    strategy:
      type: RollingUpdate
      rollingUpdate:
        maxSurge: 25%
        maxUnavailable: 25%
    progressDeadlineSeconds: 600
    revisionHistoryLimit: 10
- apiVersion: v1
  kind: Service
  metadata:
    name: order-service
    namespace: default
    labels:
      app: order-service
    creationTimestamp: "2023-04-19T07:04:22Z"
  spec:
    type: LoadBalancer
    allocateLoadBalancerNodePorts: true
    ipFamilies:
    - IPv4
    ipFamilyPolicy: SingleStack
    ports:
    - name: http
      port: 8080
      protocol: TCP
      targetPort: 8080
      nodePort: 32308
    selector:
      app: order-service
    sessionAffinity: None
    externalTrafficPolicy: Cluster
    internalTrafficPolicy: Cluster
